# fly.toml app configuration file generated for cloud-stash on 2023-08-08T19:53:00+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cloud-stash"
primary_region = "sin"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
