name: Fly Deploy
on:
  workflow_run:
    workflows: ["Lint"]
    branches: [dev]
    types: 
      - completed
jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
            cd server
            flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
